### ISSUE TITLE
Suggestion: Monster %age

### ISSUE THREAD

**Issue by SaintJason** [Xotic750/Castle-Age-Autoplayer#28]
Sorry about putting this here. I can't get onto the forum.

Here is a suggestion: Have monster damage by percentage. So if I want to put 5% (for Mission or Guild Achievement) on a monster, I can just put "5%" in rather then having to calculate myself.

**Comment by Xotic750** [comment]
I have long since stopped developing this script, and it is being handled by another. You really need to get onto the forum and check where the main repository now resides.
